# hosts.yaml
---
PE-11:
    hostname: 192.168.8.11
    groups:
        - junos
    data:
        loopback: 10.11.11.11
        unique_octet: 11
        bgp_neighbors:
            - 10.22.22.22
            - 10.33.33.33
        l3vpns:
            - name: VPN-A
              vlan: 15
            - name: VPN-B
              vlan: 25
            - name: VPN-C
              vlan: 35
        
PE-22:
    hostname: 192.168.8.22
    groups:
        - junos
    data:
        loopback: 10.22.22.22
        unique_octet: 22
        bgp_neighbors:
            - 10.11.11.11
            - 10.33.33.33
        l3vpns:
            - name: VPN-A
              vlan: 15
            - name: VPN-B
              vlan: 25
            - name: VPN-C
              vlan: 35
        
PE-33:
    hostname: 192.168.8.33
    groups:
        - junos
    data:
        loopback: 10.33.33.33
        unique_octet: 33
        bgp_neighbors:
            - 10.11.11.11
            - 10.22.22.22
        l3vpns:
            - name: VPN-A
              vlan: 15
            - name: VPN-B
              vlan: 25
            - name: VPN-C
              vlan: 35
